name: CI - Complie, Test, Deploy, and Reinit

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
    ftp_deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Deploy to Staging server
          uses: easingthemes/ssh-deploy@main
          with:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATEKEY }}
            ARGS: "-rlgoDzvc -i"
            SOURCE: "dist/"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            SCRIPT_BEFORE: |
              whoami
              ls -al
            SCRIPT_AFTER: |
              whoami
              ls -al
              echo $RSYNC_STDOUT
