name: CI - Complie, Test, Deploy, and Reinit

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  cfcompile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: cfcompile
      uses: foundeo/cfml-compiler-action@master
      with:
        cfengine: lucee@5.4.3.2

  test:
    name: Run TestBox Tests
    runs-on: ubuntu-latest
    needs: [cfcompile]  # Only run after successful compilation and code checking
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies and run tests
        uses: docker://foundeo/cfml-ci-tools:latest
        env:
            TESTKEY: ${{ vars.TESTKEY }}
        with:
          entrypoint: /opt/box/box
          args: install testbox && start && testbox run
  ftp_deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ vars.FTP_SERVER }}
          username: ${{ vars.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          exclude: |
            .git*
            .github*
            tests/*
            box.json
            commandbox-debian-6.2.0.deb

  reinit:
    name: Reinitialize Application
    runs-on: ubuntu-latest
    needs: [ftp_deploy]  # Only run after successful deployment

    steps:
      - name: Send reinit request
        run: |
          echo "Reinitializing application..."
          response=$(curl -s -o /dev/null -w "%{http_code}" "${{ vars.REINIT_URL }}")
          
          if [ "$response" -eq 200 ]; then
            echo "Application reinitialized successfully"
          else
            echo "::error::Failed to reinitialize application. HTTP Status: $response"
            exit 1
          fi